version: '3.3'

services:
  app:
    build: .
    command: uvicorn app:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - .:/home/app/
    ports:
      - 8004:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0